services:
  - type: web
    name: rpo-automation-api
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements-render.txt
    startCommand: "python -m uvicorn webapp.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: CORS_ORIGINS
        value: "chrome-extension://*,http://localhost:3000"
      - key: ENVIRONMENT
        value: production